# https://github.com/Homebrew/homebrew-bundle
# In order to speed the initial bootstrap process, this Brewfile only installs
# essentials. A more complete Brewfile is symlinked to the home directory when
# the dotfiles are installed. After the initial bootstrap is complete, run
# `brew bundle install --global`

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'thoughtbot/formulae'

# Homebrew
# https://github.com/Homebrew/brew/
brew 'bash-completion'
brew 'dockutil'
brew 'git'
brew 'git-lfs'
brew 'htop'
brew 'mas'
brew 'wget'
brew 'p7zip'
brew 'smartmontools'
brew 'syncthing', restart_service: true
brew 'xctool'
brew 'ruby'

brew 'fish'

brew 'chisel'
brew 'yt-dlp'


# homebrew-cask
# https://github.com/caskroom/homebrew-cask
cask 'chromium'
cask 'tunnelblick'
cask 'textmate'
cask 'fork'
cask 'rectangle'
cask 'smcfancontrol'
cask 'slack'

# mas-cli
# https://github.com/argon/mas
mas 'Amphetamine', id: 937984704
