# https://github.com/Homebrew/homebrew-bundle
# In order to speed the initial bootstrap process, this Brewfile only installs
# essentials. A more complete Brewfile is symlinked to the home directory when
# the dotfiles are installed. After the initial bootstrap is complete, run
# `brew bundle install --global`

# Homebrew
# https://github.com/Homebrew/brew/
brew 'bash-completion'
brew 'dockutil'
brew 'git'
brew 'git-lfs'
brew 'htop'
brew 'p7zip'
brew 'smartmontools'
brew 'syncthing', restart_service: true

brew 'fish'

brew 'chisel'
brew 'youtube-dl'


# homebrew-cask
# https://github.com/caskroom/homebrew-cask
cask 'chromium'
cask 'tunnelblick'
cask 'textmate'
cask 'fork'
cask 'virtualbox'
cask 'apptrap'
cask 'spectacle'
cask 'smcfancontrol'
cask 'steam'
